### ISSUE TITLE
Step functions - ordering

### ISSUE THREAD

**Issue by avinash1sriram** [awslabs/simple-database-archival-solution#13]
Are there are in total 9 step functions?

If yes, looks like few files are missing. If no, can we rename the files as per the order

And post archival do we delete the data in the master database?

**Comment by rui-tumble** [comment]
No. But there are 9 steps, some steps are map steps. What we can do is add information in the README.md to explain this.

No, the source database is not deleted.

**Comment by ruiscosta** [comment]
No. But there are 9 steps, some steps are map steps. What we can do is add information in the README.md to explain this.

No, the source database is not deleted.

**Comment by avinash1sriram** [comment]
If the source data is not deleted then will it make the solution complete?

**Comment by avinash1sriram** [comment]
> No. But there are 9 steps, some steps are map steps. What we can do is add information in the README.md to explain this.
> 
> No, the source database is not deleted.

If the source data is not deleted then will it make the solution complete?

This might be helpful for backups
