### ISSUE TITLE
403 when Create Archive

### ISSUE THREAD

**Issue by mmuller88** [awslabs/simple-database-archival-solution#21]
Description:
Deploying the stack and loging in works like a sharm. But when trying to press "Create Archive" I do get a weird 403.

Steps to reproduce:
1) Install the stack
2) Log into the UI
3) Create a connection and make sure it works
4) Press Fetch Tables and then "Create Archives"

Expected: Archive is created
Actual Result: The button keeps loading and I get a 403.

I attached a small gif to demonstrate.
![createArchive](https://github.com/awslabs/simple-database-archival-solution/assets/18393842/4392caa8-f8f7-401a-80eb-908e9d2217c7)

When I grab the input from the request and run the lambda directly with it it works. But it would be nice if it would work in the frontend.

Here is the response from the create Archive endpoint: 
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: VVhaGErJxFzqqYO8empNf4q_stB02HyU96kTcvj7OZFllR0aZ5Uo3Q==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by mmuller88** [comment]
I just notice that the same happens if I press the second time "Fetch Tables" instead.

**Comment by ztanruan** [comment]
The issue is related to a recent update in the permissions of one of the AWS services. We will release an update to fix the bug.
