### ISSUE TITLE
Having a lot of failed Jobs

### ISSUE THREAD

**Issue by mmuller88** [awslabs/simple-database-archival-solution#22]
I'm not sure what I can do about it but our current PostgreSQL schema seems to produce a lot of job failures. I attached a pdf to see the failed jobs. As I posted a recent 403 bug #21 it might be related to it. So I found a workaround where I intercept the create archive query and copy the payload. I then adjust the payload a bit and use it as the input for the create archive Lambda. That way I at least can create an archive. But when I run the archiving process it produces a lot of failures. 

[failingJobs.pdf](https://github.com/awslabs/simple-database-archival-solution/files/12338559/failingJobs.pdf)

The errors are like:

* IllegalArgumentException: Duplicate value for path type
* IllegalArgumentException: Duplicate value for path channel
* IllegalArgumentException: Duplicate value for path ownerid
* An error occurred while calling o123.pyWriteDynamicFrame. Unsupported case of DataType: com.amazonaws.services.glue.schema.types.StringType@7fbb0c24 and DynamicNode: timestampnode.

Any advice on how to fix those job errors?

**Comment by mmuller88** [comment]
I might be wrong but shouldn't timestamp type not be translated to timestamp in PostgreSQL as highlighted in the Readme ? https://github.com/awslabs/simple-database-archival-solution#postgresql-data-type-conversions . But that doesn't seem to be the case (see picture)

<img width="999" alt="Screenshot 2023-08-21 at 13 23 00" src="https://github.com/awslabs/simple-database-archival-solution/assets/18393842/8152c70c-47f3-4a50-9764-5b8cc3fbf73e">

**Comment by ruiscosta** [comment]
We will be releasing a fix to address this, thank you for sharing.

**Comment by ruiscosta** [comment]
Fixed with https://github.com/awslabs/simple-database-archival-solution/releases/tag/v1.1.2
