### ISSUE TITLE
A bit bigger tables getting blocked

### ISSUE THREAD

**Issue by mmuller88** [awslabs/simple-database-archival-solution#24]
The default WAF rule seems to block a payload bigger then 8kb which is reached super fast having some tables https://stackoverflow.com/a/71760098 . 

For now I will disable WAF on my deployment

**Comment by ruiscosta** [comment]
Thank you for sharing, reviewing.

**Comment by ruiscosta** [comment]
@mmuller88 
We have released a new version that also addresses this when fetching source tables.
