### ISSUE TITLE
Does SDAS support to delete data from the original DB after archiving completed ?

### ISSUE THREAD

**Issue by TinCongHuynh** [awslabs/simple-database-archival-solution#27]
I think most of need of DB archive is to take objects out of the active, operational environment and place them in a safe place for long-term maintenance. For database data this means that data is written to the archive data store and then deleted from the operational database. 

May I know does SDAS support to delete data from the operational DB after archiving completed ?

**Comment by ruiscosta** [comment]
We do not support data deletion on the source.
