### ISSUE TITLE
I'm getting SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by shubhamjain2809** [awslabs/simple-database-archival-solution#28]
<img width="856" alt="image" src="https://github.com/awslabs/simple-database-archival-solution/assets/50054860/fdbec72e-cbcd-4576-a27f-bb8341438916">

Please help me out I'm getting the above error while running  npm run build.

**Comment by ruiscosta** [comment]
What version of node are you using? It should be NodeJs >= 16

**Comment by ruiscosta** [comment]
Fixed:

Set the api gateway url for the shared development environment
After deployment of the shared development environment, create a .env.development file in the web-app folder. Replace {REACT_APP_API_URL} to your ApiGatewayUrl, include the trailing slash. This only needs to be done once.

HOST=example.com
REACT_APP_API_URL=https://{REACT_APP_API_URL}/
