### ISSUE TITLE
Connectivity Problem with PostgreSQL via the web browser UI

### ISSUE THREAD

**Issue by mhmt1420** [awslabs/simple-database-archival-solution#32]
**Problem Overview:**
I successfully deployed SDAS using the provided workshop guide titled "Deploying SDAS with AWS Cloud9 and Archiving MS SQL." However, when attempting to connect to a PostgreSQL database and entering the necessary connection information via the web browser UI, I encountered a problem. The tool failed to establish a connection to the database, despite trying different user credentials (including admin user). Unfortunately, there are no accessible LOG records or error logs to provide insights into why the connection couldn't be established.

**Issue:**
1. **Connectivity Problem with PostgreSQL via the web browser UI:**
   - *Description:* Unable to establish a connection to a PostgreSQL database via the web browser UI, even with valid connection information. No error logs or records are available to diagnose the issue.
   - *Steps to Reproduce:*
     - Deploy SDAS with AWS Cloud9.
     - Follow the workshop steps for connecting to a PostgreSQL database.
     - Encounter failure in establishing a connection with no visible error information.

2. **Lack of Logging Information:**
   - *Description:* The absence of LOG records or error logs makes it challenging to diagnose and troubleshoot connectivity issues.
   - *Request:* Provide guidance on accessing LOG records or implementing logging within SDAS to assist users in identifying and resolving connection problems.

3. **Additional Workshop Clarity for PostgreSQL:**
   - *Description:* The workshop lacks specific steps for PostgreSQL installation. This omission may cause confusion and complexity for users trying to use SDAS for PostgreSQL databases.
   - *Request:* Add a dedicated tab or section to the workshop guide with clear and concise steps for installing and configuring SDAS with PostgreSQL, ensuring a smoother user experience.

4. **Verification of Network Access:**
   - *Description:* Confirming that necessary steps have been checked and arrangements made, potentially preventing connections to RDS PostgreSQL servers.
   - *Steps Verified:*
     - Peer the two VPCs together.
     - Update the route tables.
     - Add an entry in the RDS security group to allow network access from SDAS to the private RDS database instance.

**Notes:**
- While I can connect to the database using the Cloud9 terminal interface using psql tool, the web browser UI fails to establish a connection.
- Including detailed steps for PostgreSQL installation within the workshop guide will enhance user understanding and streamline the deployment process.

Thank you for addressing these concerns and enhancing the user experience with SDAS.

**Comment by ruiscosta** [comment]
Than you for sharing, I will review the Workshop and try to reproduce the error. I will follow up with my findings.

**Comment by ruiscosta** [comment]
Connect with me on LinkedIn - https://tumble.bio/rui

I was unable to replicate your issue.
