### ISSUE TITLE
Deploy fails because of changes in S3 default options for S3 bucket 

### ISSUE THREAD

**Issue by sgopalakrishnan1980** [awslabs/simple-database-archival-solution#6]
eployment fails as a result of the new S3 bucket default settings enforced on 25.04.2023 . This is because post  this change S3 Block Public Access will be enabled, and S3 access control lists (ACLs) will be disabled by default for all new buckets.

Need to add the following changes to s3-bucket-contstructs.ts (post ln 89) and  cloudfront-s3-website-construct.ts (post ln 72 & ln 81)

 objectOwnership: s3.ObjectOwnership.OBJECT_WRITER,

[clopudfront-s3-website-constructs.txt](https://github.com/awslabs/simple-database-archival-solution/files/11408150/clopudfront-s3-website-constructs.txt)

[s3-bucket-constructs.txt](https://github.com/awslabs/simple-database-archival-solution/files/11408149/s3-bucket-constructs.txt)

**Comment by ztanruan** [comment]
Updated the cdk.json based on the latest s3 security best practices (enabling S3 Block Public Access and disabling S3 access control lists (ACLs) for all new S3 buckets)
